version: '3.3'

services:
  spill-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spill-web
    ports:
      - 8080:8080
    volumes:
      - node_modules:/app/node_modules
      - .:/app

volumes:
  node_modules: